MODEL_DIR: /home/c00502820/ckpt_ds_layer61_atp4_16p_initrouting_ata
EXE_MODE: eager  # [eager, dynamo]
ENABLE_MLA: 1
BATCH_SIZE: 1
LAYER_NUM: 10
WORLD_SIZE: 16
QUANT_MODE: 5  # [3, 4, 5]
NEXT_N: 0  # MTP [0, 1, 2]
DTYPE: bfloat16  # [float16, bfloat16]
ATTN_TP_SIZE: 4  # [1, 2, 4, 8]
EXPERTS_TP_SIZE: 1  # [1, 2]
ROUTE_SHARE_ON_SAME_CARD: 1  # [0, 1]
N_ROUTED_EXPERTS_PER_RANK: 16  # this key is valid only when ROUTE_SHARE_ON_SAME_CARD is enabled
EXPERTS_SHARE_NUM_COPY: 32    # this key is valid only when WORLD_SIZE>16 and ROUTE_SHARE_ON_SAME_CARD=0
ACTUAL_SEQ_LEN: 4096
ENABLE_CACHE_COMPILE: 0  # [0, 1]
PREFILL_OR_DECODE: prefill  # [prefill, decode]
ON_CLOUD: 0  # [0, 1]
WITH_CKPT: 1  # [0, 1]
ENABLE_PROFILE: 1  # [0, 1]
INPUT_MAX_LEN: 4096  # 9216 on the cloud. It should be no less than WORLD_SIZE*2
MAX_NEW_TOKENS: 6
SAVE_MODEL: 0 # [0, 1]
ENABLE_GMM_IN_SHARED: 0
DENSE_TP_SIZE: 4 # [2, 4, 8, 16]
KVCACHE_NZ: 1 # [0, 1]
ENABLE_SUPERKERNEL: 0  # todo, there is a bug when MTP and superkernel enabled!
ENABLE_LONG_SEQLEN: 0 # [0, 1]
MOE_USE_ALL_TO_ALL: 1  # [0, 1]  used in the prefill stage
ENABLE_PREFETCH: 0
EMBED_TP_SIZE: 16
ENABLE_COMBINE_DEQUANT: 0 # [0, 1]
ENABLE_MICRO_BATCH: 0 # [0, 1]
OPROJ_TP_SIZE: 4
ENABLE_TND: 0  # [0, 1]
SEQ_LEN_TND_LIST: [1024, 1024, 2048]  # if ENABLE_TND, sum(SEQ_LEN_TND_LIST) = INPUT_MAX_LEN
ENABLE_MLA_ALLTOALL: 1 # [0, 1]
ENABLE_WEIGHT_NZ: 1