MODEL_DIR: /workspace/j00586476/deepseekv3-lite-base-latest_bugtest
EXE_MODE: dynamo
FFN_MODE: dynamo
ENABLE_MLA: 1
BATCH_SIZE: 4320
LAYER_NUM: 10
WORLD_SIZE: 64
ATTN_DIES: 48
QUANT_MODE: 5
NEXT_N: 1
DTYPE: bfloat16
ATTN_TP_SIZE: 1
EXPERTS_TP_SIZE: 1
ROUTE_SHARE_ON_SAME_CARD: 0
N_ROUTED_EXPERTS_PER_RANK: 3
REMAINDER_ROUTER_EXPERT: 0
EXPERTS_SHARE_NUM_COPY: 4
ACTUAL_SEQ_LEN: 4096
ENABLE_CACHE_COMPILE: 0
PREFILL_OR_DECODE: decode
ON_CLOUD: 0
WITH_CKPT: 0
ENABLE_PROFILE: 1
INPUT_MAX_LEN: 1
MAX_NEW_TOKENS: 120
SAVE_MODEL: 0
ENABLE_GMM_IN_SHARED: 0
DENSE_TP_SIZE: 4
KVCACHE_NZ: 1
ENABLE_SUPERKERNEL: 0
ENABLE_LONG_SEQLEN: 0
MOE_USE_ALL_TO_ALL: 1
ENABLE_PREFETCH: 1
EMBED_TP_SIZE: 4
ENABLE_COMBINE_DEQUANT: 0
ENABLE_MICRO_BATCH: 1
OPROJ_TP_SIZE: 1
ENABLE_TND: 0
SEQ_LEN_TND_LIST:
- 1024
- 1024
- 2048
ENABLE_MLA_ALLTOALL: 0
ENABLE_WEIGHT_NZ: 1
ENABLE_GMM_TUNE_CONFIG: 1
USE_FA_TENSOR: 0
ENABLE_LOW_LATENCY: 0
SPLIT_MODE: 4
ENABLE_FA_QUANT: 1
ENABLE_BATCH_WITH_RECV: 1
MICRO_BATCH_NUMBER: 3
LAYER_OUT: FA
USE_REAL_ACTUAL_SEQ_LEN: 0
TOKEN_FILE_PATH: /home/l00653936/tokens.xlsx
ATTN_FFN_START_SYNC: 0
FFN_NEED_WAIT: 1
